version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: spotify_viz_db
    restart: unless-stopped
    user: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: spotify_viz_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: